### ISSUE TITLE
Document.updateAll not updating references

### ISSUE THREAD

**Issue by juho** [peerlibrary/meteor-peerdb#31]
I want to have some fixture data for local development which I’m inserting like so (in server/fixtures.js):

```
 var questionId0 = Question.documents.insert({
   title: "Title text"
 });

 var testAnswerId0 = Answer.documents.insert({
   question: {
     _id: questionId0
   }
 });
```

My PeerDB class definition for Answer has the Question field referenced:

```
       question: Answer.ReferenceField(Question, ['title'])
```

I see the changes being made to the answer object when I manually update the Question in the Mongo CLI, but running Document.updateAll(); after doing my insertions in fixtures.js does not seem to construct the couple of references I’d want to have while booting up.

**Comment by juho** [comment]
Ah, got it working - was something dumb like I thought. It was outside my Meteor.startup().

**Comment by mitar** [comment]
Yes, it should be after you see that observes are running.
