### ISSUE TITLE
bulkInsert removes undeclared subfields

### ISSUE THREAD

**Issue by kostko** [peerlibrary/meteor-peerdb#32]
If you have the following document definition:
```coffee
class Item extends Document
  @Meta
    name: 'Item'
    fields: =>
      foo:
        bar: @ReferenceField AnotherDocument, []
```

And you perform an `Item.documents.bulkInsert` operation on data like:
```coffee
[
  _id: "iBovvBKYBy89buvPC"
  hello: "world"
  foo:
    bar:
      _id: 'JkzTRmQpnR4Y7Qx8Q'
    fieldA: 1
    fieldB: "hello"      
]
```

Documents which will be inserted will not contain the fields `foo.fieldA` or `foo.fieldB`.

**Comment by kostko** [comment]
Hm, looks like the minimongo projection `{'foo.bar': 0}` causes the whole `foo` to be excluded instead of just `foo.bar`? And if you try to do `{'foo': 1, 'foo.bar': 0}`, there is an exception saying:
```
MinimongoError: You cannot currently mix including and excluding fields.
```

**Comment by mitar** [comment]
Pull request encouraged. :-)

**Comment by mitar** [comment]
Yea, you cannot mix things. Is it Minimongo issue?

**Comment by kostko** [comment]
Hm, no, I was wrong. The problem is not the projection, but rather the update query which does something like this:
```coffee
@update doc._id, {$set: {foo: {bar: {_id: '...'}}}}
```

And this overwrites the top-level `foo`. Instead it should be something like:
```coffee
{$set: {'foo.bar': {_id: ...}}}
```
