### ISSUE TITLE
Synchronous XMLHttpRequest warning

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-peerdb#36]
Chrome gives me this warning: 
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```
It points to this line in the stacktrace package: 
https://github.com/peerlibrary/stacktrace.js/blob/master/stacktrace.js#L351

Could it be replaced with something that doesn't give warnings? Not really a big issue, just OCD.

**Comment by mitar** [comment]
This is only during development. When you deploy (and minimize) you will not have this warning. So in production you do not get a warning.

But during development, if you have an error in `fields` function, this allows you to get a nice location of it.
