### ISSUE TITLE
Multi-server architecture

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-peerdb#39]
I'm trying to make two meteor apps talk to each other. Let's call them Master and Slave.

Each of the apps is a meteor app so it comes with its server and a client. Master.com runs the master server, and pointing the browser to Master.com return you the Master client code. Likewise for Slave server and client.

Slave client can talk to Master server just fine (from what I've tested so far). The problem is when Slave server tries to talk to Master server. Actually, just declaring the Document on the Slave server is the problem, because the server code of peerdb kicks in and tries to ensure index on the collection, but it is not really there (it is coming from a remote connection from Master). So the server throws this error:
```
W20160107-21:52:55.677(-8)? (STDERR) Error: Can only call _ensureIndex on server collections
W20160107-21:52:55.677(-8)? (STDERR)     at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:630:1)
W20160107-21:52:55.677(-8)? (STDERR)     at _ReferenceField.globals.Document._TargetedFieldsObservingField._setupTargetObservers (packages/peerlibrary_peerdb/packages/peerlibrary_peerdb.js:1261:1)
W20160107-21:52:55.677(-8)? (STDERR)     at setupTargetObservers (packages/peerlibrary_peerdb/packages/peerlibrary_peerdb.js:1907:1)
W20160107-21:52:55.677(-8)? (STDERR)     at setupObservers (packages/peerlibrary_peerdb/packages/peerlibrary_peerdb.js:1923:1)
W20160107-21:52:55.677(-8)? (STDERR)     at Document (packages/peerlibrary_peerdb/packages/peerlibrary_peerdb.js:1977:1)
```

At least that is my interpretation after quickly looking into the issue.

The way I create the document is that i send a collection to the `@Meta` function, and that collection is build with the connection option that points to another server (so even on the server, it is not local to that server).

Let me know if I should be more clear about what I'm doing and if you need a minimal test.

**Comment by mitar** [comment]
That was a great black hole. Thanks for reporting. I had to change quite a lot in the package after I started thinking about this use case (so supporting collections with custom connections).
