### ISSUE TITLE
Collection created on server even when a document has remote connection.

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-peerdb#40]
Related to #39, I now run on peerdb@0.20.0 and when inspecting the local mongo database, I still see collections created on the server, even though the connection for that Document goes to a different server.

It's not a problem since queries seem to go to the other server, just thought I'd mention that you get a lingering (unused) empty collection.

**Comment by MatejJan** [comment]
Hm, on the second try now, the extra collection was not created. Maybe I had it in the DB from before. I'll reopen if I can confirm the problem.

**Comment by mitar** [comment]
Thanks.

**Comment by mitar** [comment]
I added a test. They are not created.

**Comment by MatejJan** [comment]
:+1: Great, thanks! I'll soon try to make server-server connections to test everything out.
