### ISSUE TITLE
Name must match the class name

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-peerdb#41]
What is the purpose of collection name having to match the class name?

Right now I'm going around this like this:
```
class AB.Translation extends AT.RemoteDocument
  @Meta
    abstract: true
```
and
```
  class ArtificialBabelTranslation extends AB.Translation
    @Meta
      name: 'ArtificialBabelTranslation'

  AB.Translation = ArtificialBabelTranslation
```

Am I going to run into trouble because of this? And if no, why do I have to jump through hoops in the first place?

**Comment by MatejJan** [comment]
I just noticed I also used another (better) strategy somewhere else in the code. Posting it in case someone searches for this issue. 

So the point of doing this is that I want to access a document on some namespace (dummy) class, but have the document name reflect the namespace as well (so it doesn't clash in the database). 

Here I went about it like this:

```
class PixelDailiesTheme extends Document
  @Meta
    name: 'PixelDailiesTheme'

PixelArtAcademy.PixelDailies.Theme = PixelDailiesTheme
```

Much cleaner. I guess the ideal would still be:

```
class PixelArtAcademy.PixelDailies.Theme extends Document
  @Meta
    name: 'PixelDailiesTheme'
```

**Comment by mitar** [comment]
> What is the purpose of collection name having to match the class name?

I think this is some bad try at more strict-typing in PeerDB.

I think one alternative could also be:

```
class PixelArtAcademy.PixelDailies.Theme extends Document
  @Meta
    name: 'Theme'
    collection: new Mongo.Collection 'PixelArtAcademy.PixelDailies.Themes'
```

**Comment by MatejJan** [comment]
(As it turns out, I just found out that I wrote the first solution (first post) that way because of some other reason—I didn't want the collection to be created at that point.)

Well, as long as nothing will break using my workaround, all is good.
