### ISSUE TITLE
CRUD many-to-many relatioships between 3 interconnected collections

### ISSUE THREAD

**Issue by lobosan** [peerlibrary/meteor-peerdb#42]
Hi @mitar 

I have 3 collections: Markets, Producers and Organizations.

Markets might have many Producers and vice versa
Producers might have many Organizations and vice versa
Organizations might have many Markets and vice versa

My question is, how should I design the schemas in order to perform atomic inserts, updates and deletes? so all the information is consistent and stays in sync

Thanks in advance for any help

**Comment by dpatte** [comment]
join tables

**Comment by mitar** [comment]
Atomic inserts is not something PeerDB facilities for you in any special way. Read MongoDB [two-phase commit](https://docs.mongodb.org/manual/tutorial/perform-two-phase-commits/) documentation if you want such types of atomicity in MongoDB.

But often you do not really need atomicity. Why would you need it in this case? You want consistency, not atomicity of updates. And often you are OK with eventual consistency.

So, here you could just define something like:

```coffee
class Market extends Document
  @Meta
    name: 'Market'
    fields: =>
      producers: [@ReferenceField Producer]

class Market extends Document
  @Meta
     name: 'Market'
     fields: =>
       organizations: [@ReferenceField Organization]

class Organization extends Document
  @Meta
    name: 'Organization'
     fields: =>
       markets: [@ReferenceField Market]
```

This will make sure many-to-many references between your documents are eventually consistent.
