### ISSUE TITLE
Option to specify the mongo driver

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-peerdb#43]
Sometimes you need to connect to multiple mongo databases from the same app. That can be done by specifying the internal mongo driver when creating the collection as show [here](http://stackoverflow.com/questions/20535755/using-multiple-mongodb-databases-with-meteor-js):

```
var database = new MongoInternals.RemoteCollectionDriver("<mongo url>");
MyCollection = new Mongo.Collection("collection_name", { _driver: database });
```

This could work in PeerDB in a similar fashion that you can specify a custom collection to use.

**Comment by mitar** [comment]
Hm, so why not specifying then this `MyCollection` to PeerDB?

See here [example for custom DDP connection](https://github.com/peerlibrary/meteor-peerdb/blob/master/tests.coffee#L3946). You can do a similar thing for multiple databases, no?

But really, multiple MongoDB databases, what type of an app you are doing? ;-)

**Comment by MatejJan** [comment]
Ah, yes, I forget that you can pass exactly which collection to use directly as well.

I was going to have store purchases in a separate database than the main app db. I'm now reconsidering how useful this is. :)
