### ISSUE TITLE
PeerDB query in publication rather than always?

### ISSUE THREAD

**Issue by janat08** [peerlibrary/meteor-peerdb#51]
My understanding is that it denormalizes all the time even with auto-generators, so if it's for performance than should doing it in publications suffice? If not then auto-generators don't denormalize does the generation occur on client which would then require peerdb query on client (that is if I encoded information for indexing limitations, would rather not have to decode on server all the time)?

**Comment by mitar** [comment]
Autogenerators should be deterministic and pure. So output should be always the same, so storing that in the database improves performance and allows also querying over them.

**Comment by janat08** [comment]
What about rewriting queries

**Comment by mitar** [comment]
What about what?

**Comment by janat08** [comment]
Do you have to you really have to use PeerDB query format as per the title?

**Comment by mitar** [comment]
What is PeerDB query format?

**Comment by janat08** [comment]
Person.documents.findOne().email

**Comment by mitar** [comment]
This is just a wrapper around default Meteor queries, which uses `transform` to make an instance of the class. It has not much with denormalization. (But it knows how to make instances of nested documents.)

**Comment by janat08** [comment]
You mean this then Person.documents.findOne().comment.verbose()?

**Comment by mitar** [comment]
If `verbose` is a method on your Comment class, then yes, this should work.
