### ISSUE TITLE
Background initialization of observers or other optimizations

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-peerdb#53]
My app with 40+ document classes and many reference fields between them takes a relatively long time to start.

- 15s Meteor app startup (including build time)
- 10s PeerDB Enabling observers

And on code update:

- 3-4s build time
- 10s PeerDB Enabling observers

So it takes just long enough that you can't just change the code, switch to browser and see the results almost immediately (under 5s) so you can keep on working. _(Instead you go to another tab with Twitter or something and then 15s turns into 5min … but that's another problem.)_

Would it be possible that observers would initialize in the background, so that the server would immediately start working, and you can test your code changes (which often enough don't include any document updates, so I'm fine waiting 10 seconds before any computed fields/references are updated).

What I'm worried is that if this initialization is delayed, you'd 'miss' any updates if document changes do happen in those 10 seconds, and not do them at all (which would be a problem). But I don't have an understanding of the architecture if this is indeed a problem or how much effort this would be. So I'd appreciate a discussion on what could be done to mitigate 10s+ restart times due to use of PeerDB.

**Comment by MatejJan** [comment]
I was looking over the code to learn how things are done and got a hunch that the initial `find` (on which `observeChanges` is called) is behind this delay. That would mean that the number of document records (rather than document classes) affects initialization time, and it does turn out that is the case. On an empty database, enabling observes is practically instantaneous (no matter how many reference fields and other observers you have set up).

So the solution to my problem is to simply develop on a smaller database and am thus closing this ticket as it does not need change in PeerDB. The question still remains, if it is possible to optimize anything for working on large datasets, and one can feel free to reopen this issue if they require it.

**Comment by mitar** [comment]
Related:
* https://github.com/meteor/meteor-feature-requests/issues/88
* https://github.com/meteor/meteor/pull/9862

Yes, there is nothing to be done with what is currently available in Meteor.
